language: rust
services:
  - mysql

rust:
  - nightly

os:
  - linux

dist: trusty

install: true

script:
  - cd backend
  - sudo mysql -uroot < database_init.sql
  - mysql -uacmuser -presumca acm_manager < migrations/2019-12-11-053044_users/up.sql
  - cargo test